
extern "C" _declspec(dllimport) int AMC_set_amp_enable( BYTE axis , BYTE state);
extern "C" _declspec(dllimport) int AMC_start_t_move( BYTE axis, int pos, int vel, BYTE accel, BYTE decel );
extern "C" _declspec(dllimport) int AMC_get_command( BYTE axis );
extern "C" _declspec(dllimport) int AMC_get_position(BYTE axis );
extern "C" _declspec(dllimport) void AMC_position_clear( BYTE axis);
extern "C" _declspec(dllimport) long amc_get_io( BYTE port);
extern "C" _declspec(dllimport) long amc_get_out_io( BYTE port) ;
extern "C" _declspec(dllimport) long AMC_get_limit( BYTE port) ;
extern "C" _declspec(dllimport) int AMC_amp_fault_switch( BYTE axis );
extern "C" _declspec(dllimport) void AMC_set_e_stop( BYTE axis );
extern "C" _declspec(dllimport) void amc_v_move_stop( BYTE  axis );
extern "C" _declspec(dllimport) void amc_v_move( BYTE axis, int vel, int accel);
extern "C" _declspec(dllimport) int AMC_read_amp_state( BYTE axis) ;
extern "C" _declspec(dllimport) void AMC_amp_fault_reset( BYTE axis );
extern "C" _declspec(dllimport) int AMC_get_inmotion( BYTE axis);
extern "C" _declspec(dllimport) int AMC_get_pos_in(BYTE axis);
extern "C" _declspec(dllimport) int AMC_get_insequence( BYTE axis);
extern "C" _declspec(dllexport) bool AMC_homing_cycle(BYTE axis);
extern "C" _declspec(dllimport) int AMC_get_handle_error(BYTE axis);
extern "C" _declspec(dllimport) void AMC_out_io_toggle(BYTE port, int n);
extern "C" _declspec(dllimport) void amc_set_positive_limit(BYTE axis, int val);
extern "C" _declspec(dllimport) void AMC_set_negative_limit(BYTE axis, int val);
extern "C" _declspec(dllimport) void AMC_set_max_velocity(BYTE axis, int val);
extern "C" _declspec(dllimport) void AMC_set_accel_limit(BYTE axis, int val);
extern "C" _declspec(dllimport) void AMC_set_decel(BYTE axis, int val);
extern "C" _declspec(dllimport) void AMC_estop_clear( BYTE axis);
extern "C" _declspec(dllimport) int AMC_set_homedone( BYTE axis);
extern "C" _declspec(dllimport) int AMC_set_home_sensor( int axis, int state);
extern "C" _declspec(dllimport) int amc_set_positive_sensor( int axis, int state);
extern "C" _declspec(dllimport) int amc_set_negative_sensor( int axis, int state);
extern "C" _declspec(dllimport) int AMC_get_limit_data();
extern "C" _declspec(dllimport) void AMC_homing_start(BYTE axis, int vel);
extern "C" _declspec(dllimport) void AMC_homing_control_a(BYTE axis, int pos, int vel1, int vel2); 
extern "C" _declspec(dllimport) bool AMC_home_switch(BYTE axis);
extern "C" _declspec(dllimport)	void AMC_set_axis_direction(BYTE axis, BOOL dir);
extern "C" _declspec(dllimport) int AMC_start_r_move( BYTE axis,int pos,int vel, BYTE accel, BYTE decel );
extern "C" _declspec(dllimport) void amc_set_bit( int n);
extern "C" _declspec(dllimport) void amc_reset_bit( int n);
extern "C" _declspec(dllexport) int AMC_axis_done(BYTE axis);
extern "C" _declspec(dllimport) long AMC_get_axis_dir_info();
extern "C" _declspec(dllimport) void amc_set_positive_limit_active( BYTE axis, BOOL state);
extern "C" _declspec(dllimport) void AMC_set_home_limit_active( BYTE axis, BOOL state);
extern "C" _declspec(dllimport) int amc_usb_init(int b_no);// usb 이니셜 해주는 함수 
extern "C" _declspec(dllimport) int AMC_axis_state( BYTE axis );
extern "C" _declspec(dllimport) void AMC_clear_status( BYTE axis );
extern "C" _declspec(dllimport) int AMC_start_thread( BYTE axis );
extern "C" _declspec(dllimport) void AMC_quit_thread( BYTE axis );
extern "C" _declspec(dllimport) char*  AMC_get_id_name(byte axis);
extern "C" _declspec(dllimport) int AMC_get_board_num();
extern "C" _declspec(dllimport) int AMC_get_command_state(BYTE board);
extern "C" _declspec(dllimport) int AMC_read_usbdata( BYTE port);
extern "C" _declspec(dllimport) int AMC_clear_read_usbdata( BYTE port);
extern "C" _declspec(dllimport) void AMC_out_io_setting(BYTE port, int n, BOOL state);
extern "C" _declspec(dllimport) int AMC_start_two_axis_move( BYTE* axis,int* pos,int vel, BYTE accel, BYTE decel );
extern "C" _declspec(dllimport) int AMC_spl_line_move(byte axis, byte accel1, int pos1, int vel1,  byte accel2, int pos2, int vel2,  byte decel );
extern "C" _declspec(dllimport) int amc_init_setting(int board_num);
extern "C" _declspec(dllimport) void amc_out_io_init(BYTE port);
extern "C" _declspec(dllexport) void AMC_usb_init_VRS();
extern "C" _declspec(dllexport) int AMC_DeviceConfig_VRS();
extern "C" _declspec(dllexport) void AMC_device_close_VRS();
extern "C" _declspec(dllexport) void AMC_homing_start_VRS(BYTE axis, int vel);
