//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SeoilVision.rc
//
#define IDRESET                         3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SEOILVISION_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDR_MAINMENU                    129
#define IDD_RESULT                      130
#define IDD_INSPECT_SETTING             131
#define IDD_PRE_INSPECTION              132
#define IDD_DIALOG1                     133
#define IDD_DIALOG2                     135
#define IDI_ICO_MAIN2                   138
#define IDI_ICO_MAIN1                   139
#define IDD_DLG_TRIGGER_SETTING         141
#define IDD_SET_COLOR                   142
#define IDD_DLG_PARAMETER               143
#define IDD_DLG_COPYROI                 144
#define IDD_DLG_VIEWROI                 145
#define IDD_DLG_INSP_RESULT             146
#define IDD_DLG_RPM                     147
#define IDD_DLG_ERROR_LIST              148
#define IDC_LOADIMAGE                   1000
#define IDC_IMAGE                       1000
#define IDC_ROI1                        1003
#define IDC_TEST                        1008
#define IDC_RESULT                      1008
#define IDC_CAM1                        1010
#define IDC_MAGURI_OK                   1011
#define IDC_CAM2                        1011
#define IDC_MAGURI_SLIDE                1012
#define IDC_MAGURI_LENGTH               1013
#define IDC_VALUE                       1013
#define IDC_CHUCK_OK                    1014
#define IDC_BUTTON1                     1014
#define IDC_MINCHUCK                    1015
#define IDC_BUTTON2                     1015
#define IDC_MINCHUCK2                   1016
#define IDC_MAXCHUCK                    1016
#define IDC_JABARA_OK                   1018
#define IDC_BTN_TTEST                   1019
#define IDC_JABARA_RECOG                1019
#define IDC_JABARA_HEIGHT_LIMIT         1020
#define IDC_JABARA_NUM                  1020
#define IDC_JABARA_LENGTH               1021
#define IDC_ED_TRI1                     1021
#define IDC_JABARA_WIDTH_STDEV          1021
#define IDC_JABARA_DISTANCE_STDEV       1022
#define IDC_ED_TRI2                     1022
#define IDC_ED_TRI3                     1023
#define IDC_JABARA_LENGTH_LIMIT2        1023
#define IDC_JABARA_GRADIENT_STDEV       1023
#define IDC_RESOL                       1024
#define IDC_ED_TRI4                     1024
#define IDC_POK_OK                      1025
#define IDC_ED_RPM                      1025
#define IDC_POK                         1026
#define IDC_BTN_TRISET                  1026
#define IDC_POK_LIMIT                   1027
#define IDC_BTN_TRISETCLOSE             1027
#define IDC_INSERT_OK                   1028
#define IDC_BTN_SETTRI1                 1028
#define IDC_INSERT_SLIDE                1029
#define IDC_TRAN_NORM                   1029
#define IDC_SLIDE_LENGTH                1030
#define IDC_TRANS_TRANS                 1030
#define IDC_ANGLE_1                     1031
#define IDC_COLOR_NORM                  1031
#define IDC_ANGLELIMIT_1                1032
#define IDC_COLOR_RED                   1032
#define IDC_ANGLE_2                     1033
#define IDC_COLOR_GREEN                 1033
#define IDC_ANGLELIMIT_2                1034
#define IDC_COLOR_BLUE                  1034
#define IDC_IMUL1_OK                    1035
#define IDC_TEPE_TE                     1035
#define IDC_IMUL1_COLOR                 1036
#define IDC_TEPE_PE                     1036
#define IDC_JABARA_NEIGHBOR             1036
#define IDC_IMUL1_BRIGHT                1037
#define IDC_ETIQUETTE_OK2               1037
#define IDC_ETIQUETTE_OK                1037
#define IDC_IMUL1_OK2                   1038
#define IDC_ETIQUETTE_RECOG             1038
#define IDC_IMUL2_COLOR                 1039
#define IDC_ETIQUETTE_POSITION          1039
#define IDC_IMUL2_BRIGHT                1040
#define IDC_CAM_WIDTH                   1040
#define IDC_IMUL_PIX                    1041
#define IDC_Clear                       1042
#define IDC_IMUL_TOP_THRESHOLD          1042
#define IDC_CAM_HEIGHT                  1043
#define IDC_IMUL1_OK3                   1044
#define IDC_SET_VALUE                   1044
#define IDC_TRIGGER                     1044
#define IDC_IMUL3_COLOR                 1045
#define IDC_SET_VALUE_PARAM             1045
#define IDC_PITCH                       1045
#define IDC_IMUL3_BRIGHT                1046
#define IDC_ROI2                        1046
#define IDC_JABARA_MARGIN_OF_ERROR      1046
#define IDC_IMUL1_OK4                   1047
#define IDC_ROI3                        1047
#define IDC_IMUL_MID_THRESHOLD          1047
#define IDC_IMUL4_COLOR                 1048
#define IDC_SAVEDB                      1048
#define IDC_IMUL_JABARA_THRESHOLD       1048
#define IDC_IMUL4_BRIGHT                1049
#define IDC_DBLOAD                      1049
#define IDC_IMUL_CHUCK_THRESHOLD        1049
#define IDC_IMUL1_OK5                   1050
#define IDC_ROI4                        1050
#define IDC_IMUL_CHUCK_THRESHOLD2       1050
#define IDC_IMUL_INSERT_THRESHOLD       1050
#define IDC_IMUL5_COLOR                 1051
#define IDC_MAGURI                      1051
#define IDC_ETIQUETTE_SIZE              1051
#define IDC_IMUL5_BRIGHT                1052
#define IDC_CHUCK                       1052
#define IDC_IMUL_TOP_MASK               1052
#define IDC_IMUL1_OK6                   1053
#define IDC_JABARA                      1053
#define IDC_IMUL_MID_MASK               1053
#define IDC_IMUL6_COLOR                 1054
#define IDC_ANGLE_LEFT                  1054
#define IDC_IMUL_JABARA_MASK            1054
#define IDC_IMUL6_BRIGHT                1055
#define IDC_INSERT                      1055
#define IDC_IMUL_CHUCK_MASK             1055
#define IDC_IMUL1_OK7                   1056
#define IDC_ANGLE_RIGHT                 1056
#define IDC_IMUL_INSERT_MASK            1056
#define IDC_IMUL7_COLOR                 1057
#define IDC_IMUL_1                      1057
#define IDC_ETIQUETTE                   1057
#define IDC_IMUL_CHUCK_POS              1057
#define IDC_IMUL_INSERT_POS             1057
#define IDC_IMUL7_BRIGHT                1058
#define IDC_IMUL_2                      1058
#define IDC_JABARA_EDGE_OK              1058
#define IDC_ETQ_LEFT                    1058
#define IDC_ANGLE_DIFF                  1059
#define IDC_IMUL_3                      1059
#define IDC_INSERT3                     1059
#define IDC_ETQ_RIGHT                   1059
#define IDC_IMUL_4                      1060
#define IDC_IMUL_MID_OK                 1060
#define IDC_IMUL_5                      1061
#define IDC_IMUL_MID_PIX                1061
#define IDC_IMUL_6                      1062
#define IDC_IMUL1_JABARA_OK             1062
#define IDC_IMUL_JABARA_OK              1062
#define IDC_IMUL_7                      1063
#define IDC_IMUL_JABARA_PIX             1063
#define IDC_ROI5                        1064
#define IDC_IMUL_CHUCK_OK               1064
#define IDC_ROI1_1                      1065
#define IDC_IMUL_CHUCK_PIX              1065
#define IDC_CHK_INSP_ETQ                1066
#define IDC_IMUL_INSERT_OK              1066
#define IDC_RICHED_RESULT               1067
#define IDC_IMUL_INSERT_PIX             1067
#define IDC_IMUL_TOP_MASK2              1068
#define IDC_IMUL_TOP_MASK_COLS          1068
#define IDC_ED_THRES_MAIN               1069
#define IDC_MAGURI_ANGLE_OK             1069
#define IDC_ED_THRES_MAGURI             1070
#define IDC_MAGURI_ANGLE_GAP            1070
#define IDC_ED_THRES_CHUCK              1071
#define IDC_MID_ANGLE_OK                1071
#define IDC_ED_THRES_ANGLE              1072
#define IDC_MID_ANGLE_GAP               1072
#define IDC_ED_THRES_SATURATION         1073
#define IDC_TOP_ANGLE_OK                1073
#define IDC_ED_THRES_TRANSMAGURI        1074
#define IDC_TOP_ANGLE_GAP               1074
#define IDC_ED_IMUL_MAGURI              1075
#define IDC_CHUCK_ANGLE_OK              1075
#define IDC_ED_IMUL_JABARA              1076
#define IDC_CHUCK_ANGLE_GAP             1076
#define IDC_ED_IMUL_CHUCKSTOP           1077
#define IDC_INSERT_ANGLE_OK             1077
#define IDC_ED_IMUL_INSERTNOINSPECT     1078
#define IDC_INSERT_ANGLE_GAP            1078
#define IDC_ED_IMUL_CHUCKLR             1079
#define IDC_MAGURI_ANGLE_CONTINUOUS     1079
#define IDC_ED_IMUL_UPDOWN              1080
#define IDC_MID_ANGLE_CONTINUOUS        1080
#define IDC_ED_IMUL_INSERTUPDOWN        1081
#define IDC_TOP_ANGLE_CONTINUOUS        1081
#define IDC_ED_IMUL_INSERT_HEIGHT       1082
#define IDC_CHUCK_ANGLE_CONTINUOUS      1082
#define IDC_ED_ETIQ_CHABRIGHT           1083
#define IDC_INSERT_ANGLE_CONTINUOUS     1083
#define IDC_ED_ETIQ_LINECNT             1084
#define IDC_MAGURI_ANGLE_DIFF           1084
#define IDC_ED_ETIQ_DEVIATION           1085
#define IDC_IMUL_TOP_INSP_SIZE          1085
#define IDC_IMUL_TOP_PERSENT            1085
#define IDC_ED_ETIQ_JABARAETIQ          1086
#define IDC_IMUL_MID_MASK2              1086
#define IDC_IMUL_MID_PERSENT            1086
#define IDC_ED_ETIQ_ETIQSTOP            1087
#define IDC_IMUL_TOP_SIZE               1087
#define IDC_ED_ETIQ_INSPECTAREA         1088
#define IDC_IMUL_MID_SIZE               1088
#define IDC_BTN_APPLY                   1089
#define IDC_IMUL_ETQ_LEFT_OK            1089
#define IDC_CHK_USETRIGGER14            1090
#define IDC_IMUL_ETQ_LEFT_PIX           1090
#define IDC_ED_ETIQ_LENGTH              1091
#define IDC_MID_ANGLE_DIFF              1091
#define IDC_ED_ETC_IMGCENTER            1092
#define IDC_MID_ANGLE_HEIGHT_DIFF       1092
#define IDC_ED_ETC_CAMERAGAIN           1093
#define IDC_TOP_ANGLE_DIFF              1093
#define IDC_ED_ETC_CHUCKAVG             1094
#define IDC_TOP_ANGLE_HEIGHT_DIFF       1094
#define IDC_ED_IMUL_CHUCKWIDTH_LIMIT    1095
#define IDC_CHUCK_ANGLE_DIFF            1095
#define IDC_ED_ETC_CAMSHUTTER           1096
#define IDC_CHUCK_ANGLE_HEIGHT_DIFF     1096
#define IDC_ED_ETC_CHUCKUPSCALE         1097
#define IDC_INSERT_ANGLE_DIFF           1097
#define IDC_ED_COLORSTRAW_THRES01       1098
#define IDC_IMUL_ETQ_LEFT_THRESHOLD     1098
#define IDC_ED_ETC_CHUCKDOWNSCALE       1099
#define IDC_IMUL_ETQ_LEFT_MASK          1099
#define IDC_BTN_CANCEL                  1100
#define IDC_IMUL_ETQ_RIGHT_OK           1100
#define IDC_ED_COLORSTRAW_THRES02       1101
#define IDC_IMUL_ETQ_RIGHT_PIX          1101
#define IDC_ED_THRES_TRANSINSERT        1102
#define IDC_IMUL_ETQ_RIGHT_THRESHOLD    1102
#define IDC_ED_COLORSTRAW_THRES03       1103
#define IDC_IMUL_ETQ_RIGHT_MASK         1103
#define IDC_RADIO_TRI14                 1104
#define IDC_INSERT_ANGLE_OK2            1104
#define IDC_RADIO_TRI15                 1105
#define IDC_CHK_ROI01                   1105
#define IDC_IMUL_MID_MASK_COLS          1105
#define IDC_IMUL_MID_PERSENT2           1105
#define IDC_IMUL_MID_NOT                1105
#define IDC_CHK_ROI02                   1106
#define IDC_INSERT_ANGLE_DIFF2          1106
#define IDC_CHK_ROI03                   1107
#define IDC_INSERT_NOT                  1107
#define IDC_CHK_ROI04                   1108
#define IDC_INSERT_ANGLE_DIFF4          1108
#define IDC_INSERT_PIX                  1108
#define IDC_CHK_ROI05                   1109
#define IDC_CHK_ROI4                    1110
#define IDC_ROIBTN_2                    1112
#define IDC_ROIBTN_3                    1113
#define IDC_ROIBTN_4                    1114
#define IDC_ROIBTN_5                    1115
#define IDC_ROIBTN_6                    1116
#define IDC_ROIBTN_7                    1117
#define IDC_ROIBTN_8                    1118
#define IDC_ROIBTN_9                    1119
#define IDC_CHECK_ROI2                  1121
#define IDC_CHECK_ROI3                  1122
#define IDC_BUTTON_INSP_RESULT          1122
#define IDC_CHECK_ROI4                  1123
#define IDC_CHECK_ROI5                  1124
#define IDC_CHECK_ROI6                  1125
#define IDC_CHECK_ROI7                  1126
#define IDC_RICHEDIT_INSP_RESULT        1126
#define IDC_CHECK_ROI8                  1127
#define IDC_EDIT_RPM                    1127
#define IDC_CHECK_ROI9                  1128
#define IDC_CHECK_ROI1                  1129
#define IDC_DATETIME_START              1129
#define IDC_DATETIME_END                1130
#define IDC_BTN_WEEK                    1132
#define IDC_BTN_DAY                     1134
#define IDC_BTN_SEARCH                  1135
#define IDC_EDIT_TOTAL                  1137
#define IDC_EDIT_OK                     1138
#define IDC_MAGURI_SIDE_OK              1138
#define IDC_EDIT_NG                     1139
#define IDC_MAGURI_DIFF_RATIO           1139
#define IDC_EDIT1                       1140
#define IDC_MAGURI_MAX_LENGTH           1140
#define IDC_EDIT_OK_PER                 1141
#define IDC_IMUL_CHUCK_MASK_COLS        1141
#define IDC_EDIT_NG_PER                 1142
#define IDC_EDIT_NG_ANGLE               1143
#define IDC_EDIT_NG_POK                 1144
#define IDC_EDIT_NG_MAGURI              1145
#define IDC_EDIT_NG_ANGLE_PER           1146
#define IDC_EDIT_NG_POK_PER             1147
#define IDC_EDIT_NG_MAGURI_PER          1148
#define IDC_EDIT_NG_CHUCK               1149
#define IDC_EDIT_NG_INSERT              1150
#define IDC_EDIT_NG_ETIQUETTE           1151
#define IDC_EDIT_NG_CHUCK_PER           1152
#define IDC_EDIT_NG_INSERT_PER          1153
#define IDC_EDIT_NG_ETIQUETTE_PER       1154
#define IDC_EDIT_NG_JABARA              1155
#define IDC_EDIT_NG_JABARA_NG           1156
#define IDC_EDIT_NG_JABARA_PER          1156
#define IDC_EDIT_NG_IMUL                1157
#define IDC_EDIT_NG_IMUL_PER            1158
#define IDC_EDIT_NG_IMUL_TOP            1159
#define IDC_EDIT_NG_IMUL_MID            1165
#define IDC_EDIT_NG_IMUL_CHUCK          1166
#define IDC_EDIT_NG_IMUL_JABARA         1167
#define IDC_EDIT_NG_IMUL_INSERT         1168
#define IDM_FILE_QUIT                   32771
#define IDM_CAM_SETTING                 32772
#define IDM_INSP_SETTING                32773
#define IDM_INSP_START                  32774
#define IDM_CAMERA_SET2                 32775
#define IDM_INSP_VIEW                   32776
#define IDM_INSP_RESULT                 32777
#define IDM_INSP_SAVE                   32778
#define IDM_INSP_SETCAM                 32779
#define IDM_INSP_SETTING2               32780
#define IDM_FILE_SETUP                  32781
#define IDM_TEST_SOL                    32782
#define IDM_CAM_LIGHT                   32783
#define IDM_TEST_SAVEIMAGE              32784
#define IDM_TEST_SOL1                   32786
#define IDM_TEST_SOL2                   32787
#define IDM_FILE_OPEN                   32788
#define IDM_TEST_SAVEGRAB_IMAGE         32789
#define IDM_FILE_PARAMETER_NEWER        32790
#define IDM_CAM_VTRIGGER                32793
#define IDM_INSP_SETCOLOR               32794
#define IDM_TEST_SAVEREJECTIMAGE        32795
#define IDM_TEST_TW_RED                 32797
#define IDM_TEST_TW_YELLOW              32798
#define IDM_TEST_TW_GREEN               32799
#define ID_CAMTEST_CAMTEST              32800
#define ID_TEST_TEST                    32801
#define ID_TEST_TEST32802               32802
#define ID_32803                        32803
#define ID_32804                        32804
#define IDM_SOL_ONOFF                   32805
#define IDM_RPM                         32806
#define ID_32807                        32807
#define ID_32808                        32808
#define IDM_SOL_ON                      32809
#define ID_SOL_OFF                      32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1142
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
